[tox]
envlist =
    py{310,311,312}-django42,
    py{310,311,312}-django50,
    py{310,311,312,313}-django51,
    py{310,311,312,313,314}-django52,
    py{312,313,314}-django60
    py{312,313,314}-django61
min_version = 4.0
skip_missing_interpreters = true

[testenv]
deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6.0
    django60: Django>=6.0,<6.1
    django61: Django>=6.1,<7.0
    playwright>=1.62
    --find-links={toxinidir}/private_wheels/
    django-gdpr-cookie-consent
setenv =
    DJANGO_SETTINGS_MODULE = demo_project.settings
    DJANGO_ALLOW_ASYNC_UNSAFE = true
    PLAYWRIGHT_BROWSERS_PATH = 0
    NODE_NO_WARNINGS = 1
commands_pre =
    playwright install chromium
commands =
    python -m django test demo_project.tests --settings=demo_project.settings

